=== KornilovIgor/rts-cabins/docker/xml/cabin/state-1.0.0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://rts.unixcode.net/xml/cabin/state/1.0.0"
  xmlns="https://rts.unixcode.net/xml/cabin/state/1.0.0"
  elementFormDefault="qualified">

  <xs:element name="state">
    <xs:annotation>
      <xs:documentation>Состояние модели кабины</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vars">
          <xs:annotation>
            <xs:documentation>Маппинг переменных массива var на идентификаторы. Порядок будет
              учитываться при сопоставлении элементов массива.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="var" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>Описание одной переменной</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="brief" minOccurs="1" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>Комментарий для разработчика</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:minLength value="3" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ident">
                      <xs:annotation>
                        <xs:documentation>Идентификатор для маппинга</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="name">
                          <xs:simpleType>
                            <xs:restriction base="xs:Name">
                              <xs:minLength value="3" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== KornilovIgor/rts-cabins/src/loco/tep70/model/state.xml
<?xml version="1.0" encoding="UTF-8"?>
<state
  xmlns="http://rts.unixcode.net/xml/cabin/state/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rts.unixcode.net/xml/cabin/state/1.0.0 http://rts.unixcode.net/xml/cabin/state-1.0.0.xsd">
  <!-- ../../../../docker -->
  <!-- http://rts.unixcode.net -->

  <vars baseOffset="10">
    <offset>5</offset>
    <var>
      <brief>Таймер запуска дизеля</brief>
      <ident name="dizel_start_time" />
    </var>
    <var>
      <brief>Таймер прокачки масла</brief>
      <ident name="dizel_oil_time" />
    </var>
    <var>
      <brief>Мощность</brief>
      <ident name="power" />
    </var>
    <var>
      <private />
      <brief>Какой-то внутренний счётчик не раскрываемый для клиента</brief>
      <ident name="priv_counter" />
    </var>
  </vars>
</state>
